### ISSUE TITLE
Define Promise.any|some|every

### ISSUE THREAD

**Issue by annevk** [domenic/promises-unwrapping#13] opened 2013-08-30 10:13 UTC
I'd be fine with making the first argument an array per your then-method consistency argument.

**Comment by domenic** [comment] 2013-08-30 13:30
Oh cool, glad to hear it.

What's the difference between any and some again? Usually they mean the same thing. (E.g. C#'s [any](http://msdn.microsoft.com/en-us/library/bb534972.aspx) ~ ES's some.)

**Comment by annevk** [comment] 2013-08-30 13:34
any completes as soon as any of the passed promises completes.
some completes as soon as any of the passed promises resolves, or all are rejected.
every complete as soon as all of the passed promises resolves, or any are rejected.

**Comment by domenic** [comment] 2013-08-30 13:37
I am going to reinterpret that as:
- any settles as soon as any of the passed promises settle.
- some settles as soon as any of the passed promises are fulfilled, or all are rejected.
- every settles as soon as all of the passed promises are fulfilled, or any are rejected.

**Comment by annevk** [comment] 2013-08-30 13:39
Yeah, sorry about terminology.

**Comment by domenic** [comment] 2013-09-01 05:16
I do not care about these names very much, but in the interest of clarity, may I suggest:
- `Promise.race`: settles as soon as any of the given promises settles (in the same way as that promise).
- `Promise.any`: fulfills as soon as any of the passed promises are fulfilled, or rejects if all are rejected.
- `Promise.all`: fulfills once all of the passed promises are fulfilled, or rejects as soon as any are rejected.

**Comment by annevk** [comment] 2013-09-02 20:07
I guess if we change the signature back to array reusing all is fine again.

**Comment by domenic** [comment] 2013-09-02 20:27
I forgot that `Array.prototype` actually had an `every`. In light of that my new recommendation is either `race`/`some`/`every` or `race`/`any`/`all`. The former tries to mimic `Array.prototype` names where possible whereas the latter divorces from those names entirely.

My main concern is that using both "some" and "any" to mean different things is too confusing, and I think "race" is a pretty good name for the first behavior.

**Comment by Nathan-Wall** [comment] 2013-09-02 21:29
The following are the functions and signatures I've used in the past.  They're possibly over-abstract b/c they support use cases which are hardly ever used, but the extra arguments are in all cases optional:

`all(promises, state='fulfilled')` Resolves when all promises reach the specified state (fulfilled by default but could be  "rejected" or "resolved" (meaning either state)).  Fails as soon as one promise reaches the other state. The value it's resolved with will be an array of all values from the array of promises in the same order in which they existed in the array of promises.  If rejected, the value will be the value from the first promise which generated the rejection.

`some(promises, state='fulfilled', count=1)` Resolves when a certain number of promises reach the specified state or is rejected as soon as that's impossible (if count is 3 and you pass in 5 promises and the state is "fulfilled", will be rejected after 3 promises are rejected).  The value it's resolved with will be an array of the values from the promises which reached the specified state _in the order in which they reached the state_.  If rejected, will be an array of values in order of the promises which reached the other state.

`any(promises, state='fulfilled')` Just like some except _count_ is not an argument and the resolution value is not an array.  Since it will only ever look for one promise, it can resolve directly with the value from that promise, for ease of use.

`filter(promises, state='fulfilled')` Waits for all promises to resolve.  Resolves with an array of all promises which reached the specified state _in resolution order_ (if none did, will resolve with an empty array).

**Comment by domenic** [comment] 2013-09-03 02:14
Unrelated to naming: I think I'm going to make these accept any iterable, but return a promise for an array. Notably, I don't see any reason to also allow non-iterable array-likes (e.g. `{ length: 2, 0: "item 0" }`).

**Comment by domenic** [comment] 2013-09-03 03:42
What should "settles as soon as any of the given promises settles" and "fulfills as soon as any of the passed promises are fulfilled, or rejects if all are rejected" do when given an empty iterable? I would lean toward fulfilling with `undefined`, but returning a forever-pending promise is arguably more natural. Notably @erights's concurrency strawman's `Q.race` returns a forever-pending promise.

**Comment by erights** [comment] 2013-09-03 04:16
I recommend only two:

Promise.all -- fulfills with the array once all of the passed promises are fulfilled, or rejects with the first reason to be noticed as soon as any are rejected. For the empty array, all the passed promises are indeed fulfilled, so fulfills with the empty array.

Promise.race -- settles as soon as any of the given promises settles (in the same way as that promise). For the empty array, non of the promises in the empty array ever settles, to the returned promise is indeed forever pending.

I understand the potential need for the others, and have on rare occasions encountered some. FWIW, I have never encountered the need for Promise.any (fulfills as soon as any of the passed promises are fulfilled, or rejects if all are rejected) specifically, even though I can imagine cases where I would. However, they are rare enough that, for the subset-for-immediate-dom-needs purpose of this repository, I think the others can wait until we have some experience. Lots can be added between short term dom needs and eventual ES7.

**Comment by annevk** [comment] 2013-09-03 13:26
I'm fine with @erights subset. Again, less likely means we can ship more short term.

**Comment by juandopazo** [comment] 2013-09-03 13:55
> For the empty array, all the passed promises are indeed fulfilled, so fulfills with the empty array.

I came here to say that.

\o/ To everything in this thread.

**Comment by tabatkins** [comment] 2013-09-03 15:33
Yup, fine with these two for right now.  I really like the `race` name.  I'd prefer the `some`/`every` naming over `any`/`all` solely for the existing Array precedent.

**Comment by slightlyoff** [comment] 2013-09-04 19:08
Please. Stop. We have many names for these methods. `some` and `every` were picked for Array-likeness and because nothing else was un-punny. The only thing that matters about any of this is that the names are _STABLE_. That we are contemplating changing them again is just O_o.

**Comment by annevk** [comment] 2013-09-04 20:47
We are changing the signature per an argument Domenic made a while back so changing the names is reasonable and probably more compatible.

I agree though that we have to stop changing, but I think having this last round of minor changes will get us there with more agreement and better design than if we push through the older material.

**Comment by erights** [comment] 2013-09-04 20:53
> "If you want a happy ending, that depends, of course, on where you stop your story." 
> - Orson Wells. 

Which names are changes and which are stable choices, depends, of course, on where you start your story.

In any case, I agree with @annevk .

**Comment by spankyj** [comment] 2013-09-05 04:00
Please allow these to accept/return objects as well as arrays. In WinJS land we have found it endlessly useful to be able to name the various incoming asynchronous values you are waiting on and then refer to them by name in the next portion of your operation.

For instance, only today I was writing a demo app for a discussion that went and retrieved stock data and wrote code that went something like:

WinJS.Promise.join({
    quote: getQuote(symbol),
    chart: getChartData(symbol),
}).then(function (results) {
    results.quote.opening // do something with the quote info
    results.chart.dataPoints // do something with the chart info
});

**Comment by domenic** [comment] 2013-09-05 04:05
@spankyj most other promise libraries have avoided such extra because of the various edge cases involved. For example, what do you propose to do for the following cases:

``` js
var x = Object.assign([], { expando: Promise.resolve(1), 5: Promise.resolve(2) });
var y = { length: 5, 0: Promise.resolve(1), 6: Promise.resolve(2) };
var z = { length: Promise.resolve(1), width: Promise.resolve(2) };
var a = []; a.__proto__ = Error.prototype; a[0] = Promise.resolve(1);
var b = {}; b.__proto__ = Error.prototype; b.expando = Promise.resolve(1);
var c = {}; c.__proto__ = Array.prototype; c[0] = Promise.resolve(1); c.length = 2;
var d = document.createElement("div"); d.expando = Promise.resolve(3);
```

**Comment by spankyj** [comment] 2013-09-05 04:18
Well... 

Our join (all/every being discussed here) took the easy way out of simply defining itself in terms of Object.keys and using array-ness simply for determining the form of the result. We reasoned that the shallow nature of the query was acceptable due to the fact that the instances involved were likely to (almost?) always be transient in nature and really represented code structure more often than data structure.

Our any (any/race being discussed here) is an odd ball, and in fact I'm not sure that anyone uses its return value in a meaningful way and more often we see it used simply as a latch to delay further processing (e.g. don't show some UI until you have at least one thing to show). The return value of our any is a object which is a tuple of the key of the settled promise and the promise which has settled. I don't know why it is the promise instead of the value, might be a bug but is too late to change now for us...

**Closed as completed** 2013-09-05 04:45 UTC
Labels: es-manifestation

**Comment by nyuichi** [comment] 2013-09-06 10:47
The door for further discussion on changeng the names "race" and "all" is already closed?

**Comment by annevk** [comment] 2013-09-06 10:49
@wasabiz, unless you have a particular compelling argument for something else, yes. These are the names championed by popular libraries. The Array analogy doesn't hold on closer inspection, and race and all are nice and short, and pretty descriptive.

**Comment by nyuichi** [comment] 2013-09-06 10:58
I agree almost all the opinions here but one thing I feel some uncomfortable is that their parts of speech are different from each other: "race" is a verb OTOH "all" is an adjective. I prefer some other pairs such as `any`/`all` or `race`/`join`.

**Comment by annevk** [comment] 2013-09-06 11:00
That is a good point, thanks! I somewhat doubt we'll be able to keep picking consistent words going forward though. Hmm.

**Comment by nyuichi** [comment] 2013-09-06 11:53
"race" appears to have been somehow popular in this thread so it may be a better choice to pick verbs as the method names. That's why I prefer `race`/`join` over `any`/`all`. (In addition, taking care of the compatibility, there are a large number of verbs that can be used as names but this is not the case for adjs, I've ever seen only a few limited adjectives (any, some, all, etc) are adopted for function names...)

**Comment by erights** [comment] 2013-09-06 13:21
History aside, I can see the case for this meaning of join. But we already have a long history of using "all" for this meaning and some history of using "join" for eventual equality:

http://wiki.ecmascript.org/doku.php?id=strawman:concurrency#q.join
http://research.google.com/pubs/pub40673.html
http://erights.org/talks/thesis/markm-thesis.pdf section 19.5
And IIUC the latest version of Q, though not yet documented on the Q API page.

This eventual equality operation is sufficiently similar and different enough to cause confusion. I expect we will eventually add this eventual equality operator, and "join" is the perfect name for it.

I do not think we should reopen this.

**Comment by domenic** [comment] 2013-09-06 14:00
Just to add to the anecdotes: in my experience I have never found a need for `race` or (Mark's) `join`. (Although I understand he has found some use for both in his research papers.) `all`, and to a lesser extent [`allSettled`](https://github.com/kriskowal/q/wiki/API-Reference#promiseallsettled), are the only combinators I have ever found occasion to use.

As such, the only thing I care about regarding `race` is clear names; `race` is by far the clearest name for what it does, and in particular both `some` and `any` are misleading for reasons I can rehash at length if I need to but would prefer to let lie.

**Comment by nyuichi** [comment] 2013-09-06 14:26
Thank you guys for the explanation. Two questions:
1. If you think there is no need for 'race' at all, why is 'race' introduced at this time? (I was thinking this draft is a kind of minimalistic one.)
2. I don't see any reason of the misleading 'any' and 'some', could you tell me? (Only the biggest one is ok...)

**Comment by domenic** [comment] 2013-09-06 14:38
> If you think there is no need for 'race' at all, why is 'race' introduced at this time? (I was thinking this draft is a kind of minimalistic one.)

That's just my experience. The original DOM promises spec included it (under the confusing name `any`), and Mark's concurrency strawman includes it (under `race`), so we're including it for now.

> I don't see any reason of the misleading 'any' and 'some', could you tell me? (Only the biggest one is ok...)

For `some`, the problem is that the `Array.prototype` analogy does not hold up. There is no callback predicate function, and truthiness vs. falsiness is not a good analogy to fulfillment vs. rejection. `Array.prototype.some` works on the _ordinally_-first truthy, whereas `Promise.race` works on the _chronologically_-first fulfilled _or_ rejected.

For `any`, part of the problem is that "any" and "some" are largely synonyms; other languages in fact use "any" for ES's "some." That aside, if we were to interpret "any" as a counterpart to `Promise.all`, which has established semantics, then it wouldn't behave like `Promise.race` does at all, but instead would be the "there exists" to `Promise.all`'s "for every." That is, it would return a promise that is fulfilled with the first chronological fulfillment value, but only rejects if all passed in promises reject.

**Comment by spankyj** [comment] 2013-09-06 15:08
In the case of a tie I assume that race devolves into ordinally-first? For example, if the input promises are already settled?

**Comment by domenic** [comment] 2013-09-06 15:12
Yes.

**Comment by nyuichi** [comment] 2013-09-07 03:09
> The original DOM promises spec included it (under the confusing name any)

So we have a history of using `any` to some extent as well, right? Mark quoted the histories of `all` and `race` to deal with the choice and (forgetting the discussion if the `any`  is confusing or not) if you're ignoring the histroy of  `any`, it does not make sense.

> but only rejects if all passed in promises reject.

Why not? That's true that adopting the name `any` we have to determine the meaning to be a straight counterpart to `all`, but being a counterpart only when fulfilling is good enough, isn't it? Rejecting is a kind of processing failure that represents it's impossible to do something no more, it is somehow rational for `any` to return a promise if no more than 1 passed promise rejects.

**Comment by domenic** [comment] 2013-09-07 03:37
> So we have a history of using any to some extent as well, right?

This name never saw use outside of spec land, so I'm not sure I'd call it a "history" as much as a "misstep."

> but being a counterpart only when fulfilling is good enough, isn't it

No, it definitely isn't.

> Rejecting is a kind of processing failure that represents it's impossible to do something no more

That's not what rejection means; it's an asynchronous exception. Your mental model is confusing your terminology.

**Comment by nyuichi** [comment] 2013-09-07 03:50
> No, it definitely isn't.

Could you tell me the reason?

> That's not what rejection means; it's an asynchronous exception

But an _exception_. Exceptions are not of normal state.

**Comment by domenic** [comment] 2013-09-07 03:52
Because having it only work in a similar way to `all` half the time would be unacceptably confusing. Also, since all is "for all," having any not be "there exists" would be just bizarre.
