### ISSUE TITLE
Add Promise.fromGenerator

### ISSUE THREAD

**Issue by cscott** [domenic/promises-unwrapping#93] opened 2014-02-12 21:20 UTC
It would be nice if the ES6 spec could include the 'missing piece' which links Promises and Generators: a function which makes a promise-returning function from a generator which yields promises.  The code for this is small, but nontrivial to write from scratch.

From https://github.com/cscott/prfun/blob/master/lib/index.js#L438-L463 (and lifted from `Q.async`):

``` js
 Promise.fromGenerator = function(makeGenerator) {
    return function() {
      var generator, callback, errback;
      function continuer(verb, arg) {
        var result;
        try {
          result = generator[verb](arg);
        } catch (exception) {
          return Promise.reject(exception);
        }
        if (result.done) {
          return result.value;
        } else {
          return Promise.cast(result.value).then(callback, errback);
        }
      }
      generator = makeGenerator.apply(this, arguments);
      callback = continuer.bind(continuer, "next");
      errback = continuer.bind(continuer, "throw");
      return callback();
    };
  };
```

Similar code is in bluebird's `Promise.coroutine`, Q's `Q.async`, when's `generator.lift`, etc.

I think it would be worthwhile to standardize the naming of this function.  The only disagreement on behavior seems to be that several implementations add an implicit Promise.all if you yield an array, so that you can do:

``` js
[result1, result2] = yield [task1(), task2()];
```

instead of

``` js
[result1, result2] = yield Promise.all([task1(), task2()]);
```

**Comment by domenic** [comment] 2014-02-12 21:24
Hi @cscott,

I appreciate your interest, but ES6 promises are done (much like the rest of the spec), and only editorial or bugfixes will occur. This repo is for tracking that work, and not for additions.

If you wish to submit proposals for ES7, I'd suggest using the es-discuss mailing list. However, I think for ES7 the preferred approach is going to be [introducing `async`/`await`](https://github.com/lukehoban/ecmascript-asyncawait), instead of propagating the elegant hack that generators + promises compose into.

**Comment by domenic** [comment] 2014-02-12 21:24
Also, dupe of #17.

**Closed as completed by domenic** 2014-02-12 21:24 UTC

**Comment by cscott** [comment] 2014-02-12 21:42
Sure, thanks for the links.
